### ISSUE TITLE
Cannot find module './glossary' - @mswjs/interceptors

### ISSUE THREAD

**Issue by guirak** [artmizu/nuxt-prometheus#36]
Hello, 

I'm having the following error when adding the module to my nuxt 3 app : 

Cannot find module './glossary' Require stack: - /[...]/@mswjs/interceptors

Is the module still working ? 

Regards

**Comment by artmizu** [comment]
@guirak

hello, thank you for using the package. I'm not sure you're question is still valid or not, but:
1. try to update the package to the last version, i published new one a little while
2. try to LTS version of Node, for example 20.13.0 
3. Try to use last version of Nuxt

For the future investigations would you kindly send additional information e.g Nuxt version, NodeJS version and so on?

For now i closed the issue due to inactivity, but if you'll face the problem again - you should open the new issue.

**Comment by guirak** [comment]
Hi. Thank you for your reply. I have put this topic pending. I will try again when I have a moment
